language: node_js
node_js: 7
cache:
  yarn: true
  directories:
  - node_modules
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- yarn
script: echo "Deploying!"
before_deploy: npm run build
install:
  - npm install -g firebase-tools
after_sucess:
  - firebase deploy --token $FIREBASE_TOKEN