language: node_js
sudo: required
dist: trusty
node_js: 7
cache:
 yarn: true
 directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- yarn install
script:
  - yarn run lint
script: echo "Deploying!"
before_deploy: 
  - yarn run build
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master
  project: gdghyderabad-19758
  token:
    secure: $FIREBASE_TOKEN